### ISSUE TITLE
Improve [bw_plug] when oik-plugins post type defined locally

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/oik-bob-bing-wide#19]
The [bw_plug] shortcode should be improved to provide easier links to a referenced plugin.
In a multisite environment it might also be nice if it were able to to detect the 'correct' site. 

Also fix...

`
Warning: Attempt to assign property of non-object in C:\apache\htdocs\wordpress\wp-content\plugins\oik-bob-bing-wide\shortcodes\oik-plug.php on line 241
`

**Comment by bobbingwide** [comment]
The changes  in 40a7b42 are ok for a simple link to a plugin but not for a table of plugins where we want to see data from WordPress.org. Until the code is implemented using a better class structure a pragmatic solution would be to used the cache method to load data for WordPress plugins.

**Comment by bobbingwide** [comment]
Note: We still get the warning message.

**Comment by bobbingwide** [comment]
Well, since this issue isn't yet closed I may as well add this new message.
It occurs when the locally cached plugin_info is from oik-plugins and doesnt contain a value for downloaded. The following function would appear to need to be improved.
```
function oikp_get_downloaded( $post, $version ) { 
  return( "" );
} 
```
or the routine that calls it. 

/home/herb/public_html/wp-content/plugins/oik-bwtrace/includes/bwtrace-actions.php(279:2) bw_trace_error_handler(1) 120 3 2020-01-30T15:26:15+00:00 0.227250 0.000205 cf=genesis_loop,genesis_entry_content,the_content 11453 73 20664 29360128/29360128 768M F=887 err W3TC\Generic_Plugin::ob_callback,ob_gzhandler,autoptimizeMain::end_buffering
Array

    [0] => (integer) 2
    [1] => (string) "Warning: number_format() expects parameter 1 to be float, string given"
    [2] => (string) "/home/herb/public_html/wp-includes/functions.php"
    [3] => (integer) 397
@#:0 337 508<table class="bw_plug"><tbody><tr><th class="name">Plugin name and description</th><th class="links">Plugin links</th><th class="vtdlut">Version, total downloads, last update, tested</th></tr><tr><td class="name"><strong>oik-css</strong><br />Internal CSS styling</td><td class="links"><a class="plugin" href="https://www.oik-plugins.com/oik-plugins/oik-css/" title="Link to the oik-css (oik-css: Internal CSS styling) plugin">oik-css</a><br /></td><td class="vtdlut"><span class="version">0.9.0</span><br />
0. bw_lazy_backtrace /home/herb/public_html/wp-content/plugins/oik-batch/libs/bwtrace.php:108 0
1. bw_backtrace /home/herb/public_html/wp-content/plugins/oik-bwtrace/includes/bwtrace-actions.php:286 0
2. bw_trace_error_handler(2,number_format() expects parameter 1 to be float, string given,/home/herb/public_html/wp-includes/functions.php,397,array) /home/herb/public_html/wp-content/plugins/oik-bwtrace/includes/bwtrace-actions.php:0 5
3. number_format(,0,.,,) /home/herb/public_html/wp-includes/functions.php:397 4
4. number_format_i18n(,0) /home/herb/public_html/wp-content/plugins/oik-bob-bing-wide/shortcodes/oik-plug.php:794 2
5. bw_format_plug_table(oik-css,unsupported,object) /home/herb/public_html/wp-content/plugins/oik-bob-bing-wide/shortcodes/oik-plug.php:72 3
6. bw_plug(array,,bw_plug) /home/herb/public_html/wp-content/plugins/oik/oik-add-shortcodes.php:207 3

**Comment by bobbingwide** [comment]
Workaround was to delete the transient data cached for the plugin from oik-plugins.com and reset the entry for the plugin.

**Comment by bobbingwide** [comment]
Problem happened again on oik-plugins.com and oik-plugins.co.uk 
Time to apply the fix!

**Comment by bobbingwide** [comment]
Still getting 
```
Attempt to assign property 'oik_server' of non-object in 
oik-plugins.com@plugins/oik-bob-bing-wide/shortcodes/oik-plug.php on line 243
```

visiting /oik-faq/cart-weight-based-plugin-need/


23-Nov-2024 08:12:16 UTC] PHP Fatal error:  Uncaught Error: Attempt to assign property "oik_server" on string in /home/customer/www/oik-plugins.co.uk/public_html/wp-content/plugins/oik-bob-bing-wide/shortcodes/oik-plug.php:243
```
Stack trace:
#0 /home/customer/www/oik-plugins.co.uk/public_html/wp-content/plugins/oik-bob-bing-wide/shortcodes/oik-plug.php(181): bw_get_oik_plugins_info('oik-weight-zone...')
#1 /home/customer/www/oik-plugins.co.uk/public_html/wp-content/plugins/oik-bob-bing-wide/shortcodes/oik-plug.php(923): bw_get_plugin_info_cache2('oik-weight-zone...')
#2 /home/customer/www/oik-plugins.co.uk/public_html/wp-content/plugins/oik-bob-bing-wide/shortcodes/oik-plug.php(55): bw_get_plugin_info('oik-weight-zone...', true)
#3 /home/customer/www/oik-plugins.co.uk/public_html/wp-content/plugins/oik/libs/oik-shortcodes.php(229): bw_plug(Array, '', 'bw_plug')
#4 /home/customer/www/oik-plugins.co.uk/public_html/wp-includes/shortcodes.php(434): bw_shortcode_event(Array, '', 'bw_plug')
#5 /home/customer/www/oik-plugins.co.uk/public_html/wp-content/plugins/oik-css/includes/shortcodes-earlier.php(118): do_shortcode_tag(Array)
#6 [internal function]: do_shortcode_tag_earlier(Array)
#7 /home/customer/www/oik-plugins.co.uk/public_html/wp-content/plugins/oik-css/includes/shortcodes-earlier.php(95): preg_replace_callback('/\\[(\\[?)(bw_plu...', 'do_shortcode_ta...', '\n<p><strong>Q.<...')
#8 /home/customer/www/oik-plugins.co.uk/public_html/wp-includes/class-wp-hook.php(324): do_shortcode_earlier('\n<p><strong>Q.<...')
#9 /home/customer/www/oik-plugins.co.uk/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters('\n<p><strong>Q.<...', Array)
#10 /home/customer/www/oik-plugins.co.uk/public_html/wp-includes/post-template.php(256): apply_filters('the_content', '<!-- wp:paragra...')
#11 /home/customer/www/oik-plugins.co.uk/public_html/wp-content/themes/genesis/lib/structure/post.php(486): the_content()
#12 /home/customer/www/oik-plugins.co.uk/public_html/wp-includes/class-wp-hook.php(324): genesis_do_post_content('')
#13 /home/customer/www/oik-plugins.co.uk/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#14 /home/customer/www/oik-plugins.co.uk/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#15 /home/customer/www/oik-plugins.co.uk/public_html/wp-content/themes/genesis/lib/structure/loops.php(119): do_action('genesis_entry_c...')
#16 /home/customer/www/oik-plugins.co.uk/public_html/wp-content/themes/genesis/lib/structure/loops.php(38): genesis_standard_loop()
#17 /home/customer/www/oik-plugins.co.uk/public_html/wp-includes/class-wp-hook.php(324): genesis_do_loop('')
#18 /home/customer/www/oik-plugins.co.uk/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#19 /home/customer/www/oik-plugins.co.uk/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#20 /home/customer/www/oik-plugins.co.uk/public_html/wp-content/themes/genesis/lib/framework.php(66): do_action('genesis_loop')
#21 /home/customer/www/oik-plugins.co.uk/public_html/wp-content/themes/genesis/single.php(15): genesis()
#22 /home/customer/www/oik-plugins.co.uk/public_html/wp-includes/template-loader.php(106): include('/home/customer/...')
#23 /home/customer/www/oik-plugins.co.uk/public_html/wp-blog-header.php(19): require_once('/home/customer/...')
#24 /home/customer/www/oik-plugins.co.uk/public_html/index.php(17): require('/home/customer/...')
#25 {main}
  thrown in /home/customer/www/oik-plugins.co.uk/public_html/wp-content/plugins/oik-bob-bing-wide/shortcodes/oik-plug.php on line 243
```

**Comment by bobbingwide** [comment]
I spent an age attempting to reproduce the problem in s.b/oikcom.

In the end I changed the code in `oik-plugins-feed.php` to echo an unexpected string before the (expected) serialized response.
This produced the Fatal error in the front end. 
Now that I've reproduced the problem I can implement the fix.
Which is that the code needs to check that the result is an object before attempting to assign the property.
